title: Home
tab: blog
body: |
  <ul class="posts">
    {% for post in site.posts limit:8 %}
      <li>
        <header>
          <div class="calendar">
            <span class="day">{{ post.date | date: "%d" }}</span>
            <span class="month">{{ post.date | date: "%b" | upcase }}</span>
          </div>
          <div class="name">
            <h2 class="title"><a href="{{ post.url }}">{{ post.title }}</a></h2>
            <span class="description">{{ post.description }}</span>
          </div>
        </header>
        <div class="post">
          {{ post.content }}
        </div>
      </li>
    {% endfor %}
  </ul>