on: push
name: Build and push
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: docker://node:latest
      with:
        args: npm install
    - name: Master
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: Build
      uses: docker://node:latest
      with:
        args: ./node_modules/.bin/webpack -p --output-path=build
    - name: GitHub Action for Google Cloud
      uses: actions/gcloud/auth@8ec8bfa
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      with:
        args: '&& gsutil cp -R build/* gs://kern.io'
